/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#69ff87",
        "on-primary-fixed": "#1a1c1f",
        "on-primary-container": "#838487",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb4aa",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary": "#000000",
        "primary-fixed": "#e2e2e6",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#930005",
        "outline": "#76777b",
        "outline-variant": "#c6c6ca",
        "on-secondary-fixed": "#002108",
        "on-surface": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#3ce36a",
        "on-secondary": "#ffffff",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "primary-fixed-dim": "#c6c6ca",
        "on-secondary-container": "#00732c",
        "secondary-container": "#5cfd80",
        "primary": "#000000",
        "surface-container": "#edeeef",
        "tertiary-fixed": "#ffdad5",
        "on-surface-variant": "#45474a",
        "on-error": "#ffffff",
        "surface": "#f8f9fa",
        "secondary": "#006e2a",
        "surface-tint": "#5d5e62",
        "surface-variant": "#e1e3e4",
        "inverse-primary": "#c6c6ca",
        "surface-container-highest": "#e1e3e4",
        "tertiary-container": "#410001",
        "on-tertiary-container": "#f9362c",
        "on-secondary-fixed-variant": "#00531e",
        "on-tertiary-fixed": "#410001",
        "surface-container-low": "#f3f4f5",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed-variant": "#45474a",
        "error-container": "#ffdad6",
        "primary-container": "#1a1c1f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "24px",
        "base": "8px",
        "container-padding": "20px",
        "gutter": "16px",
        "stack-sm": "12px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-currency": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "monetary-md": ["18px", { lineHeight: "22px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        "card": "0 4px 20px rgba(0,0,0,0.04)",
        "card-hover": "0 8px 30px rgba(0,0,0,0.08)",
        "float": "0 8px 24px rgba(0,0,0,0.15)",
        "nav": "0 -4px 20px rgba(0,0,0,0.04)",
      },
      backdropBlur: {
        xs: "4px",
      },
    },
  },
  plugins: [],
};
